spring.application.name=25_26_ING_3_ISI_FR_groupe_5
spring.datasource.url=jdbc:postgresql://localhost:5432/25_26_ING_ISI_FR_groupe_5
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
server.port=8080

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG
# Configuration email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votre.email@gmail.com
spring.mail.password=votre-mot-de-passe-applicatif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true